package com.ssafy.bjbj.api.member.enums;

public enum ActivityType {
    BOOKLOG_CREATE, BOOKLOG_UPDATE, BOOKLOG_DELETE,
    READING_GROUP_BOARD_CREATE, READING_GROUP_BOARD_UPDATE, READING_GROUP_BOARD_DELETE,
    BOOK_REVIEW_CREATE, BOOK_REVIEW_UPDATE, BOOK_REVIEW_DELETE;
}
